# Set up the environment
Install Python, NumPy, Pandas, Matplotlib, and Seaborn. For that, you can use the instructions from 06-environment.md.

# Q1. Pandas version
What version of Pandas did you install?

You can get the version information using the __version__ field:

In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.__version__

'2.3.1'

# Getting the data
For this homework, we'll use the Car Fuel Efficiency dataset (https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv)
Or just open it with your browser and click "Save as...".

Now read it with Pandas.

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
df.head(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217

# Q2. Records count
How many records are in the dataset?

In [6]:
df.shape[0]

9704

# Q3. Fuel types
How many fuel types are presented in the dataset?

In [7]:
df['fuel_type'].nunique()

2

# Q4. Missing values
How many columns in the dataset have missing values?

In [8]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

There are 4 columns have missing values.

# Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [20]:
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

# Q6. Median value of horsepower
Find the median value of the horsepower column in the dataset.

Next, calculate the most frequent value of the same horsepower column.

Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

Now, calculate the median value of horsepower once again.

Has it changed?

In [10]:
ori_median_horse_power = df['horsepower'].median()
ori_median_horse_power

np.float64(149.0)

In [11]:
mode_horse_power = df['horsepower'].mode()[0]
mode_horse_power

np.float64(152.0)

In [12]:
df = df.fillna(value={'horsepower': mode_horse_power})
after_filled_median_horse_power = df['horsepower'].median()
after_filled_median_horse_power

np.float64(152.0)

Yes, it increased

# Q7. Sum of weights
Select all the cars from Asia

Select only columns vehicle_weight and model_year

Select the first 7 values

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Invert XTX.

Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the sum of all the elements of the result?

In [13]:
X = df.loc[df['origin'] == 'Asia', ['vehicle_weight', 'model_year']].head(7).values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [14]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [15]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [16]:
w =np.linalg.inv(XTX).dot(X.T).dot(y).sum()
w

np.float64(0.5187709081074016)