In [43]:
import numpy as np
import pandas as pd

In [44]:
pd.__version__

'2.3.1'

In [45]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [46]:
df.head(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217

In [47]:
df.shape

(9704, 11)

In [48]:
df['fuel_type'].nunique()

2

In [49]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [50]:
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [51]:
ori_median_horse_power = df['horsepower'].median()
ori_median_horse_power

np.float64(149.0)

In [52]:
mode_horse_power = df['horsepower'].mode()[0]
mode_horse_power

np.float64(152.0)

In [53]:
df = df.fillna(value={'horsepower': mode_horse_power})
after_filled_median_horse_power = df['horsepower'].median()
after_filled_median_horse_power

np.float64(152.0)

In [54]:
X = df.loc[df['origin'] == 'Asia', ['vehicle_weight', 'model_year']].head(7).values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [55]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [56]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [57]:
w =np.linalg.inv(XTX).dot(X.T).dot(y).sum()
w

np.float64(0.5187709081074016)